@echo off
REM This batch file cleans up auxiliary files generated by LaTeX.

echo Cleaning up LaTeX auxiliary files...

if exist *.aux del /q *.aux
if exist *.bbl del /q *.bbl
if exist *.blg del /q *.blg
if exist *.log del /q *.log
if exist *.out del /q *.out
if exist *.synctex.gz del /q *.synctex.gz
if exist *.toc del /q *.toc
if exist *.snm del /q *.snm
if exist *.nav del /q *.nav

echo Cleanup complete.
